@baseUrl = https://8080-cabreralucas-apip2-lwn0zzjslsw.ws-us114.gitpod.io

###
GET {{baseUrl}}/comentarios

###
POST {{baseUrl}}/comentarios
Content-Type: application/json

{
    "titulo" : "Imaginação 3",
    "texto" : "Algumas palavras escritas 3",
    "usuario" : {"id" : 3}
}

###
PUT {{baseUrl}}/comentarios/2
Content-Type: application/json

{
    "titulo" : "Imaginação Alterada 2",
    "texto" : "Algumas palavras escritas alteradas",
    "usuario" : {"id" : 2}
}


###
DELETE {{baseUrl}}/comentarios/2