@baseUrl = https://8080-cabreralucas-apip2-lwn0zzjslsw.ws-us114.gitpod.io
###
GET {{baseUrl}}/login

###
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email" : "algumacoisa3@hotmail.com",
    "senha" : "123456"
}

###
PUT {{baseUrl}}/login/1
Content-Type: application/json

{
    "email" : "algumacoisa@gmail.com",
    "senha" : "654321"
}