@baseUrl = https://8080-cabreralucas-apip2-lwn0zzjslsw.ws-us114.gitpod.io

###
GET {{baseUrl}}/usuarios

###
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
    "nome" : "Nick do Jogador 3",
    "nomeExibicao" : "Apelido do Jogador 3",
    "login" : {"id" : 3}
}

###
PUT {{baseUrl}}/usuarios/1
Content-Type: application/json

{
    "titulo" : "Nick do Jogador Alterado",
    "texto" : "Apelido do Jogador Alterado",
    "login" : {"id" : 1}
}