@baseUrl = https://8080-cabreralucas-apip2-rklgb0e2g13.ws-us110.gitpod.io

###
GET {{baseUrl}}/usuarios

###
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
    "nome" : "Nick do Jogador",
    "nomeExibicao" : "Apelido do Jogador",
    "login" : {"id" : 1}
}

###
PUT {{baseUrl}}/usuarios/1
Content-Type: application/json

{
    "titulo" : "Nick do Jogador Alterado",
    "texto" : "Apelido do Jogador Alterado",
    "login" : {"id" : 1}
}